export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_CHECK_LOADING = "AUTH_CHECK_LOADING";

export const TOOGLE_CREATE_CLASS_MODAL = "TOOGLE_CREATE_CLASS_MODAL";
export const TOOGLE_JOIN_CLASS_MODAL = "TOOGLE_JOIN_CLASS_MODAL";
export const TOOGLE_UNENROLL_CLASS_MODAL = "TOOGLE_UNENROLL_CLASS_MODAL";

export const CREATE_CLASS_LOADING = "CREATE_CLASS_LOADING";
export const CREATE_CLASS_SUCCESS = "CREATE_CLASS_SUCCESS";

export const JOIN_CLASS_LOADING = "JOIN_CLASS_LOADING";
export const JOIN_CLASS_SUCCESS = "JOIN_CLASS_SUCCESS";
export const JOIN_CLASS_FAILED = "JOIN_CLASS_FAILED";
export const JOINED_ALREADY = "JOINED_ALREADY";

export const FETCH_CLASS_LOADING = "FETCH_CLASS_LOADING";
export const FETCH_CLASS_SUCCESS = "FETCH_CLASS_SUCCESS";
export const FETCH_CLASS_ERROR = "FETCH_CLASS_ERROR";

export const FETCH_SINGLE_CLASS_LOADING = "FETCH_SINGLE_CLASS_LOADING";
export const FETCH_SINGLE_CLASS_ERROR = "FETCH_SINGLE_CLASS_ERROR";
export const FETCH_SINGLE_CLASS = "FETCH_SINGLE_CLASS";

export const ADD_CLASS_CONTENT_LOADING = "ADD_CLASS_CONTENT_LOADING";
export const ADD_CLASS_CONTENT = "ADD_CLASS_CONTENT";

export const FETCH_CLASS_CONTENTS_LOADING = "FETCH_CLASS_CONTENTS_LOADING";
export const FETCH_CLASS_CONTENTS_SUCCESS = "FETCH_CLASS_CONTENTS_SUCCESS";

export const ADD_COMMENT_IN_CLASS_CONTENT_LOADING = "ADD_COMMENT_IN_CLASS_CONTENT_LOADING";
export const ADD_COMMENT_IN_CLASS_CONTENT = "ADD_COMMENT_IN_CLASS_CONTENT";

export const FETCH_CLASS_COMMENTS_LOADING = "FETCH_CLASS_COMMENTS_LOADING";
export const FETCH_CLASS_COMMENTS = "FETCH_CLASS_COMMENTS";

export const SELECTED_CLASS_TO_UNENROLL = "SELECTED_CLASS_TO_UNENROLL";
export const UNENROLL_CLASS_LOADING = "UNENROLL_CLASS_LOADING";
export const UNENROLL_CLASS_SUCCESS = "UNENROLL_CLASS_SUCCESS";
export const UNENROLL_CLASS_FAILED = "UNENROLL_CLASS_FAILED";
